ALTER TABLE public.tenant
ALTER COLUMN tenant_id
DROP DEFAULT;

ALTER TABLE public.tenant
ALTER COLUMN tenant_id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE public.branch
ALTER COLUMN branch_id
DROP DEFAULT;

ALTER TABLE public.branch
ALTER COLUMN branch_id ADD GENERATED ALWAYS AS IDENTITY;